### ISSUE TITLE
Let's cooperate!

### ISSUE THREAD

**Issue by gdubicki** [Roche/gitlab-configuration-as-code#9]
Hi!

I noticed that you recently started this project which is very similar to what we do in https://github.com/egnyte/gitlabform .

How about we join forces and create a single, better tool together? :)

**Comment by filipowm** [comment]
Hi there @gdubicki !

Sorry I'm responding just now, I was out for a while :)

Idea sounds very very good, let me just take a deeper look and we can discuss this in two weeks (next week I'm out).

**Comment by gdubicki** [comment]
For now I added a link to GCasC to our [README](https://github.com/egnyte/gitlabform#comparison-to-similar-apps). :)
